# Generated by Django 3.2.8 on 2022-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='created_post',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
