# Generated by Django 3.2.8 on 2022-07-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewBlogApp', '0004_remove_created_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_post',
            name='user',
            field=models.CharField(default='raja', max_length=100),
        ),
    ]
