# Generated by Django 3.2.8 on 2022-07-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewBlogApp', '0005_created_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='created_post',
            new_name='user_created_blog',
        ),
    ]
