# Generated by Django 3.2.8 on 2022-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewBlogApp', '0006_rename_created_post_user_created_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_created_blog',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
