# Generated by Django 3.2.8 on 2022-07-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewBlogApp', '0007_alter_user_created_blog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_created_blog',
            options={'ordering': ['date']},
        ),
    ]
